name: OneLine
version: 1.0
author: SkyZoneMC
api: [3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
main: SkyZoneMC\OneLine\OneLine
description: 'OneLine in Minecraft'
commands:
    ol:
        description: 'Main-Command'
        permission: 'ol.admin'
    leave:
        description: 'Leave the game'
        aliases: [spawn, leave]
    stats:
        description: 'Stats command'
    addtickets:
        description: 'Adds stats-resetters to an player'
        permission: 'ol.tickets'
    hub:
        description: 'Back to hub'